97 update dspecs to work with new scema
conrad-blucher-institute/semaphore pull request #100
Opened 2023-10-19 01:54 UTC by bestrada33

Test feels like overkill. Need to comment out the line below to run the test or else it gives an error. (Make sure to remove comment when done!)
![image](https://github.com/conrad-blucher-institute/semaphore/assets/74482285/39599fda-0b75-469a-9a55-e95f32e4d5d7)

Also, be sure to `pip install dotenv` if you haven't already. Isn't in this branches `requirements.txt`, but should be in the newer branches.

2023-10-19 22:26 UTC, matdenkas requested changes
Up to you if you wanna fix these. They wont cause bugs.

2023-10-19 22:26 UTC, matdenkas commented on src/ModelExecution/inputGatherer.py
> +
The .get accessor returns none if the key is not found. Thus there is no reason to except a KeyError here

2023-10-19 22:26 UTC, matdenkas commented on src/ModelExecution/dspec.py
> +        return f'[Input] -> name: {self.name}, location: {self.location}, source: {self.source}, series: {self.series}, type: {self.type}, datum: {self.datum}, range: {self.range}'
Only dataClassifications was removed from the object but both were removed from the __str__ method

2023-10-19 22:26 UTC, matdenkas commented on src/ModelExecution/dspec.py
> +        return f'[Input] -> name: {self.name}, location: {self.location}, source: {self.source}, series: {self.series}, type: {self.type}, datum: {self.datum}, range: {self.range}'
Same thing here, unit is still in the object

2023-10-19 22:45 UTC, bestrada33 commented on src/ModelExecution/inputGatherer.py
> +
Should I just use .get for unit too then? Instead of KeyError?

2023-10-19 22:48 UTC, bestrada33 commented on src/ModelExecution/inputGatherer.py
> +
Nvm yeah using .get now instead

2023-10-19 22:48 UTC, matdenkas commented on src/ModelExecution/inputGatherer.py
> +
It is my understanding that yes you should

2023-10-23 15:58 UTC, matdenkas approved these changes
LGTM

2023-10-23 16:11 UTC, abeasley1722 approved these changes

2023-10-23 17:45 UTC, merged