96 add filtering by interval to selection method
conrad-blucher-institute/semaphore pull request #106
Opened 2023-10-25 01:04 UTC by matdenkas

2023-10-25 02:37 UTC, bestrada33 commented on src/SeriesStorage/SeriesStorage/SQLAlchemyORM.py
Need documentation for `timeIntervalConstraint`

2023-10-25 02:50 UTC, bestrada33 commented on src/SeriesStorage/SeriesStorage/SQLAlchemyORM.py
> +    def select_input(self, seriesDescription: SeriesDescription, timeDescription : TimeDescription, timeIntervalConstraint: timedelta = None) -> Series:
Need documentation for `timeIntervalConstraint`

2023-10-25 02:51 UTC, bestrada33 requested changes
Need documentation for `timeIntervalConstraint`

2023-10-25 03:03 UTC, bestrada33 approved these changes
Test looks great. Small errors fixed. LGTM

2023-10-27 00:09 UTC, lovelysandlonelys requested changes
When running the test files two tests fail for the same reason: 
![image](https://github.com/conrad-blucher-institute/semaphore/assets/91633941/89943242-60de-4cf0-92e3-592a53fa1870)

2023-10-27 01:27 UTC, matdenkas commented
> When running the test files two tests fail for the same reason: ![image](https://user-images.githubusercontent.com/91633941/278502841-89943242-60de-4cf0-92e3-592a53fa1870.png)

![image](https://github.com/conrad-blucher-institute/semaphore/assets/64288827/21620c0a-834e-409e-ae1a-34a1de8b2e78)

2023-10-27 02:22 UTC, bestrada33 approved these changes
LGTM again

2023-11-01 04:00 UTC, merged