107 refactor seriesprovider to reflect new schema
conrad-blucher-institute/semaphore pull request #108
Opened 2023-10-25 02:47 UTC by matdenkas

I had to change a lot in the request_input. We will need to talk about it at some point, because basically if you don't provide an interval it cant validate weather data is complete or not. This is highly important for dspecs as single point input specifications will have to still provide an interval! Which is weird!

I couldn't write testings thanks to relative imports. Ill bring it up at the meeting!

2023-10-27 03:00 UTC, bestrada33 commented on src/SeriesProvider/SeriesProvider.py
> +            errSeries = Series(seriesDescription, timeDescription, False)
Am I crazy or shouldn't `False` go before `timeDescription`? Assuming `False` is for `isComplete`

2023-10-27 03:03 UTC, bestrada33 requested changes
https://github.com/conrad-blucher-institute/semaphore/pull/108/files#r1374021416

2023-10-30 17:53 UTC, bestrada33 commented on src/SeriesProvider/SeriesProvider.py
> +            seriesStorageResults = self.seriesStorage.select_input(seriesDescription, timeDescription).data
Didn't know you could do .data at the end of a function call. How cool.

2023-10-30 17:57 UTC, bestrada33 approved these changes
Couldn't find anything obvious. Wish we could test. Should be fine though.

2023-11-01 04:06 UTC, matdenkas commented on src/SeriesProvider/SeriesProvider.py
> +            seriesStorageResults = self.seriesStorage.select_input(seriesDescription, timeDescription).data
🤓 Fluent Interface - https://en.wikipedia.org/wiki/Fluent_interface

2023-11-01 05:02 UTC, merged