66 create ndfd ingestion class
conrad-blucher-institute/semaphore pull request #121
Opened 2023-11-01 19:12 UTC by bestrada33

The class is by no means done, but I want to merge it into schemaUpgradeRefactor such that I have the most updated code. Is not expected to work. Will have errors. Going to split up these issues on the project board after merge.

2023-11-03 06:29 UTC, matdenkas commented on src/DataIngestion/DataIngestion/NDFD.py
> +        response = self.__api_request(url)
You might want to add a check here that checks if the response is None, and then returns None

2023-11-03 06:30 UTC, matdenkas commented on src/DataIngestion/DataIngestion/NDFD.py
> +Time = TypeVar('Time')
Can you please go over this tomorrow? This is really cool and I dont think I under stand it

2023-11-03 06:30 UTC, matdenkas commented on src/DataIngestion/DataIngestion/NDFD.py
> +        if(seriesRequest.dataLocation == 'SBirdIsland'): # NOTE:: Temporary
The methodology to get lat and lon is in the db, if you are ready to add it

2023-11-03 06:31 UTC, matdenkas commented on src/DataIngestion/DataIngestion/NDFD.py
> +    def zipped(self) -> ZippedDataset[Time, Data]:
What black magic is this?????????? This is very cool but looks very complicated

2023-11-03 06:31 UTC, matdenkas commented on src/DataIngestion/DataIngestion/NDFD.py
> +    """Convert iso to unix timestamp in milliseconds.  E.g., 2019-04-11T19:00:00-05:00 → 1555027200000"""
If you got this code from somewhere you should tag it with @source

2023-11-03 06:34 UTC, matdenkas requested changes

2023-11-03 06:34 UTC, matdenkas commented on src/DataIngestion/DataIngestion/NDFD.py
> +        inputs = []
You aren't doing anything to filter via an interval. So you would over return over sampled data to SeriesProvider. Im not sure the structure of NDFD if there is no risk of getting oversampled data then this is fine, but if not then we need a clause filtering by an interval here

2023-11-03 07:23 UTC, bestrada33 commented on src/DataIngestion/DataIngestion/NDFD.py
> +Time = TypeVar('Time')
I wish I made that. That was Brian or Niall

2023-11-03 07:24 UTC, bestrada33 commented on src/DataIngestion/DataIngestion/NDFD.py
> +        if(seriesRequest.dataLocation == 'SBirdIsland'): # NOTE:: Temporary
Is there an example you can show me?

2023-11-03 07:34 UTC, bestrada33 commented on src/DataIngestion/DataIngestion/NDFD.py
> +    def zipped(self) -> ZippedDataset[Time, Data]:
Not mine, but I agree

2023-11-03 07:35 UTC, bestrada33 commented on src/DataIngestion/DataIngestion/NDFD.py
> +    """Convert iso to unix timestamp in milliseconds.  E.g., 2019-04-11T19:00:00-05:00 → 1555027200000"""
I put the tag at the very top. Most of this is from Brian. I only added Semaphore related stuff and a couple other additions.

2023-11-04 02:01 UTC, bestrada33 commented on src/DataIngestion/DataIngestion/NDFD.py
> +    ms = int(datetime.strptime(time_str, '%Y-%m-%dT%H:%M:%S%z').timestamp()) * 1000
Should I remove the multiplication by 1000?

2023-11-04 02:05 UTC, bestrada33 commented on src/DataIngestion/DataIngestion/NDFD.py
> +        inputs = []
I don't think interval will ever come in to play for NDFD. The dates are just too all over the place.

2023-11-10 06:29 UTC, lovelysandlonelys approved these changes
most of this is going over my head : D but it seems to work the way it's supposed to

2023-11-10 06:29 UTC, lovelysandlonelys commented on src/DataIngestion/DataIngestion/NDFD.py
> +    def __create_url_pattern(self, seriesRequest: SeriesDescription, timeRequest: TimeDescription, product: str) -> str:
do function description? the name is pretty intuitive so maybe it doesn't need one?

2023-11-10 07:10 UTC, bestrada33 commented on src/DataIngestion/DataIngestion/NDFD.py
> +    def __create_url_pattern(self, seriesRequest: SeriesDescription, timeRequest: TimeDescription, product: str) -> str:
I probably could. Honestly saw the other ingestion classes didn't have any, so I didn't put any. ¯\_(ツ)_/¯ Adding some now

2023-11-10 07:42 UTC, abeasley1722 commented on src/DataIngestion/DataIngestion/NDFD.py
> +        base_url = 'https://graphical.weather.gov/xml/sample_products/browser_interface/ndfdXMLclient.php?whichClient=NDFDgen'
I've been told its good practice to add large strings like this to the beginning of the code, but I could be wrong

2023-11-10 07:42 UTC, abeasley1722 commented on src/tests/test_NDFD.py
> +        NOTE:: This test depends on DBM.insert_lat_lon_test('SBirdIsland', 'South Bird Island', None, '27.4844', '-97.318') pre=existing in db
Is it meant to be "pre-existing"?

2023-11-10 16:48 UTC, bestrada33 commented on src/tests/test_NDFD.py
> +        NOTE:: This test depends on DBM.insert_lat_lon_test('SBirdIsland', 'South Bird Island', None, '27.4844', '-97.318') pre=existing in db
Yes! "Copying Matthew's comment" moment

2023-11-10 16:49 UTC, bestrada33 commented on src/DataIngestion/DataIngestion/NDFD.py
> +        base_url = 'https://graphical.weather.gov/xml/sample_products/browser_interface/ndfdXMLclient.php?whichClient=NDFDgen'
Did they say why?

2023-11-11 03:34 UTC, merged