Entrypoint
conrad-blucher-institute/semaphore pull request #135
Opened 2023-11-09 07:00 UTC by lovelysandlonelys

A few things: 
- So, I wrote this with the assumption being that the database is already set up. I'm not sure if that should be the case or not? Since this is supposed to be like the easy way for new people to run semaphore there should probably be something that initializes the database right? But for this initial version run all the tests twice before testing arguments because we need the database.
-  I did attempt to write a test for this but I couldn't find much on mocking command line interfaces the way that I wrote mine so any thoughts on that would be appreciated!
- In the meeting last week there was a brief discussion about if the calculate reference time function should be placed in inputGatherer or somewhere else so maybe also keep that in mind? Joy and I put it where we thought it made most sense but we were thinking about a specific use case.

To Test: 
- python3 semaphoreRunner.py -h (for instructions)
- python3 semaphoreRunner.py -d test_dspec (to run test model now)

2023-11-10 05:11 UTC, bestrada33 commented on data/dspec/test_dspec.json
> +    "timingInfo":{
I don't know what it is, but 'timing' throws me off. I can't think of a better word right now though.

2023-11-10 05:11 UTC, bestrada33 commented on semaphoreRunner.py
> +        print(result)
print statements!!!

2023-11-10 05:14 UTC, bestrada33 commented on semaphoreRunner.py
> +        print(result)
Bunch of print statements! I think these should be logs?  Also, could probably just log `result` and `result.data` once after the if/else statements. Since no matter what they will be assigned

2023-11-10 05:17 UTC, bestrada33 commented on semaphoreRunner.py
> +        #checking that the past time passed is formatted correctly (stolen from beto)
Appreciate the shoutout! (capitalize the 'B' though ;)  )

2023-11-10 05:23 UTC, bestrada33 commented on semaphoreRunner.py
> +        if execution_time >= datetime.now():
Shouldn't this be `<` if it is checking if it is in the past? Instead of `>=`

2023-11-10 05:38 UTC, bestrada33 commented on semaphoreRunner.py
> +def main(args=None):
Why is `args` optional? Is this like a thing? Genuinely asking because I don't know.

2023-11-10 06:25 UTC, bestrada33 commented on src/ModelExecution/inputGatherer.py
> +    def calculate_referenceTime(self, execution :datetime) -> datetime:
This seems to work well

2023-11-10 06:32 UTC, lovelysandlonelys commented on data/dspec/test_dspec.json
> +    "timingInfo":{
vibe. we kinda just named it the first thing we thought of but i can see how it might be kinda vague. maybe something like intervalSpecifications? since it's mostly just information on interval?

2023-11-10 06:36 UTC, lovelysandlonelys commented on semaphoreRunner.py
> +        #checking that the past time passed is formatted correctly (stolen from beto)
o7

2023-11-10 06:56 UTC, bestrada33 commented on data/dspec/test_dspec.json
> +    "timingInfo":{
Ahhhhh, maybe it won't matter. All the rest in dspec.py are {blahblah}Info anyways.

2023-11-10 07:00 UTC, bestrada33 requested changes
This branch should be fine, just the small changes I commented on.

I made an item for the `post_process_prediction` bugs in the Projects Board

2023-11-10 07:05 UTC, lovelysandlonelys commented on semaphoreRunner.py
> +def main(args=None):
so, i made this change when i was looking for a way to write a test for the runner and all the examples I found did this so that they could call the function in the testing file

2023-11-16 21:35 UTC, abeasley1722 commented on src/semaphoreRunner.py
> +    if executionTime == None:
I've read that we should use "is" when comparing python constants like None

2023-11-16 23:22 UTC, matdenkas commented on src/semaphoreRunner.py
> +    if executionTime == None:
It is a better practice, Granted I do == None all the time but when have I ever done anything the right way. Its pure optimization though, saving a call to an __eq__. All that means is that doing == None and is None will give you the same result in every situation, just is is faster as it will check typing information rather than data.

2023-11-16 23:23 UTC, matdenkas commented on src/semaphoreRunner.py
> +    if executionTime == None:
I hope that toneyly comes across right

2023-11-16 23:55 UTC, matdenkas requested changes
`PS C:\Dev\semaphore> python3 ./src/semaphoreRunner.py
Traceback (most recent call last):
  File "C:\Dev\semaphore\src\semaphoreRunner.py", line 20, in <module>
    from src.ModelExecution.modelWrapper import ModelWrapper
ModuleNotFoundError: No module named 'src'
PS C:\Dev\semaphore>`

You need to adjust import statements when you move files

2023-12-08 20:05 UTC, matdenkas approved these changes

2023-12-18 18:14 UTC, merged