284 Operationalization of all Inundation months and small change of modelwrapper to reflect tf layer changes
conrad-blucher-institute/semaphore pull request #299
Opened 2024-04-28 05:06 UTC by abeasley1722

### Changes:

1. Created the dspec for each month of the inundation models
2. Shortened the names of the dspecs for each model as some exceeded the character limit that can be added to the database
3. Added each model to the crontab
4. Changed a small part of the modelwrapper as we can no longer get input_shapes from layers in the newer versions of tensorflow. firstlayer and last layer were not used in any other parts of the code, so I deleted them.

If crontab does not work on your WSL just run the "docker exec command... " from the crontab in the parent directory of Semaphore.

2024-05-03 03:17 UTC, lovelysandlonelys requested changes
I think that the versions for all the new files should just be 1.0.0. rather than 1.0.1 (which is kinda a nasty change sorry). Otherwise everything looks good to me 👍🏻

2024-05-03 03:17 UTC, lovelysandlonelys commented on data/dspec/Inundation/August/ar_inundation_aug_12h.json
> +    "modelVersion": "1.0.1",
Isn't this technically version 1.0.0 because we've never had the inundation models loaded before?

2024-05-03 03:17 UTC, lovelysandlonelys commented on src/ModelExecution/modelWrapper.py
> +
Would you be able to explain this change to me?

2024-05-03 03:18 UTC, lovelysandlonelys commented on src/ModelExecution/modelWrapper.py
> +
OHhh wait I just read the title, this is the bug fix for the tensorflow update?

2024-05-05 22:47 UTC, lovelysandlonelys approved these changes
LGTM 👍🏻

2024-05-08 15:42 UTC, bestrada33 commented on src/ModelExecution/modelWrapper.py
> +        log(f'input shape {shape}')
Should this still be here?

2024-05-08 15:53 UTC, bestrada33 commented on data/dspec/Inundation/July/ar_inundation_july_12h.json
> +    "modelName": "ar_inundation_july_12h",
I see that you switched from using the full months "apil" to just the first 3 letters "apr". Can you do that for june and july (so "jun" & "jul") too? Just so they can all have the same format. (I need this for the script I'm making for CBOCP that automatically switches the model based on the month.)

2024-05-08 15:54 UTC, bestrada33 commented on data/dspec/Inundation/September/ar_inundation_sept_12h.json
> +    "modelName": "ar_inundation_sept_12h",
Same thing here as above. Can you use "sep" instead of "sept"?

2024-05-09 03:15 UTC, bestrada33 commented on data/cron/semaphore.cron
> +5 * * * * mkdir -p ./logs/$(date "+\%Y")/$(date "+\%m")/Inundation/September && docker exec semaphore-core python3 src/semaphoreRunner.py -d ./Inundation/September/ar_inundation_sep_48h.json >> ./log
September is spelt wrong in all of these. Also, any reason for using the full month name for the cron logs?

2024-05-09 19:22 UTC, lovelysandlonelys approved these changes

2024-05-10 15:42 UTC, merged