Created the interface for PostProcessing
conrad-blucher-institute/semaphore pull request #301
Opened 2024-04-30 03:14 UTC by abeasley1722

If it seems like I tinkered with more files than necessary, it's because I merged in the dspec 2.0 updates to this branch.

2024-04-30 18:33 UTC, matdenkas commented on src/PostProcessing/PostProcessing.py
> +    def post_process_data(self, preprocessedData: list[Series], postProcessCall: str ) -> list[Series]:
postProcessCall is a class defined in my work, not a string. This can be changed when we add it all together though

2024-04-30 18:35 UTC, matdenkas commented on src/PostProcessing/PostProcessing.py
> +    def post_process_data(self, preprocessedData: list[Series], postProcessCall: str ) -> list[Series]:
If you wanted to do it now, yould need to pull my PR into yours or merge my pr and rebase your PR

2024-04-30 18:35 UTC, matdenkas commented on src/PostProcessing/PostProcessing.py
> +            module_name = 'PostProcessingClasses'
Constants should be in all caps: `MODULE_NAME`

2024-04-30 18:43 UTC, matdenkas requested changes

2024-04-30 18:43 UTC, matdenkas commented on src/PostProcessing/PostProcessing.py
> +# version 2.0
1.0?

2024-05-01 05:44 UTC, lovelysandlonelys reviewed
the things matthew commented on make sense for improvements, otherwise looks good to me

2024-05-08 00:37 UTC, closed without merging