Refactored and created the logic for interpolation
conrad-blucher-institute/semaphore pull request #307
Opened 2024-05-09 02:37 UTC by abeasley1722

### Changes:

Refactor(Pairprogrammed with Savannah):

- Added maxGapDistance to the dependent series object
-  Refactored dspec parser to add the maxGapDistance 
- Refactored input gatherer 
- Refactored series provider

Added Interpolation Logic(Pairprogrammed with Beto):

In SeriesProvider:
- Created the interpolation function
- Created the check_gap_distance function
- Created the fill_in_date_gaps function

2024-05-09 02:50 UTC, bestrada33 commented on src/SeriesProvider/SeriesProvider.py
> +         filled_merged_df = fill_in_date_gaps(merged_df,timeDescription.fromDateTime, timeDescription.toDateTime, timeDescription.interval,)
remove the comma after timeDescription.interval

2024-05-09 02:58 UTC, bestrada33 commented on src/SeriesProvider/SeriesProvider.py
> +         largerThanMaxGapDistance, rows_with_nan = check_gap_distance(filled_merged_df, seriesDescription.maxGapDistance, timeDescription.interval)
I understand the intent, but I don't think we need to return the rows_with_nan. It makes it look messy and there's no reason to print them below either.

2024-05-09 02:59 UTC, bestrada33 commented on src/SeriesProvider/SeriesProvider.py
> +                    Rows with NaN only: {rows_with_nan}
What I mentioned above. Can remove this

2024-05-09 03:06 UTC, bestrada33 commented on src/SeriesProvider/SeriesProvider.py
> +         filled_merged_df = fill_in_date_gaps(merged_df,timeDescription.fromDateTime, timeDescription.toDateTime, timeDescription.interval,)
Also, found an issue with this. Forgot to come back to it. The fill_in_date_gaps will add the missing timeVerified index column and make the rest of the columns NaN. So, we need to fill in the NaNs for the rest of the columns. (i.e dataUnit, timeGenerated, longitude, latitude.) dataValue will be interpolated later.

2024-05-09 03:07 UTC, abeasley1722 commented on src/SeriesProvider/SeriesProvider.py
> +         largerThanMaxGapDistance, rows_with_nan = check_gap_distance(filled_merged_df, seriesDescription.maxGapDistance, timeDescription.interval)
Dangg. Will do.

2024-05-09 03:11 UTC, bestrada33 commented on src/SeriesProvider/SeriesProvider.py
> +        return False, rows_with_nan
Just return False. (Also worth mentioning that False is "good" in this case, since it means that the interpolation was successful.)

2024-05-09 03:12 UTC, abeasley1722 commented on src/SeriesProvider/SeriesProvider.py
> +        sure that there isn't a distance between two NAN values that is larger than the maxGapDistance.
Thankss

2024-05-09 18:51 UTC, matdenkas requested changes
Very nice work! I dont like how dirty our SeriesDesc object is getting, but thats a problem for another day. This was a lot of code and I am thankful to be part of a team that took care of it for me 🫡

2024-05-09 18:51 UTC, matdenkas commented on src/SeriesProvider/SeriesProvider.py
>                      {seriesDescription} \n
I dont think we should be logging here. This is a silent action. If we had better logging we could make this verbose, and in the future we might want to have tracking on predictions to see if interpolation was used. However, this makes it look like the input was failed, and there is no mention of if interpolation happened. Personally I would only log a failure if we can't interpolate. But if you do want to log here, then it should mention if interpolation happened or not.

2024-05-09 19:02 UTC, lovelysandlonelys requested changes

2024-05-09 19:02 UTC, lovelysandlonelys commented on src/SeriesProvider/SeriesProvider.py
> +    def interpolate_series(seriesDescription: SeriesDescription, timeDescription: TimeDescription, validated_merged_result: Series) -> Series:
We have to pass self to use internal function so interpolate_series, fill_in_date_gaps, and check_gap_distance have to be private I think. (I can fix this and push it!)

2024-05-09 19:02 UTC, lovelysandlonelys commented on src/SeriesProvider/SeriesProvider.py
> +         merged_df.set_index("timeVerified", inplace=True)
there is smth going on here but I'm not sure what it is: 
File "/app/src/SeriesProvider/SeriesProvider.py", line 105, in __interpolate_series
    merged_df.set_index("timeVerified", inplace=True)
  File "/usr/local/lib/python3.11/dist-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pandas/core/frame.py", line 6012, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['timeVerified'] are in the columns"
05/09/24 18:57:10: Semaphore fin!

2024-05-09 19:29 UTC, abeasley1722 commented on src/SeriesProvider/SeriesProvider.py
>                      {seriesDescription} \n
This log was here before our changes. The only log we added for this task is on line 112. I see what you mean. Now that there is interpolation its probably not necessary anymore.

2024-05-10 17:57 UTC, bestrada33 commented on src/SeriesProvider/SeriesProvider.py
> +    def  __check_gap_distance(df: pd.DataFrame, maxGapDistance: timedelta, interval: timedelta) -> bool:
This also needs `self` added as an argument.

2024-05-10 17:57 UTC, bestrada33 commented on src/SeriesProvider/SeriesProvider.py
> +    def __fill_in_date_gaps(df : pd.DataFrame , start_date : datetime , end_date : datetime , interval : timedelta ) -> pd.DataFrame:
This also needs `self` added as an argument.

2024-05-10 17:58 UTC, bestrada33 commented on src/SeriesProvider/SeriesProvider.py
> +    def interpolate_series(seriesDescription: SeriesDescription, timeDescription: TimeDescription, validated_merged_result: Series) -> Series:
Nice catch and thank you for fixing it!

2024-05-10 19:02 UTC, lovelysandlonelys commented
Notes From Meeting: 
- change seconds value of maxGapDistance to correspond to points since that's what we use to describe series in dspec and might make the method more generalized
- passing a lot to the interpolation method, maybe should only be passing the series
- should the method return the full series (create a new series with all the gaps filled) or return only the values that were interpolated
- To change the isComplete value we should be passing it to the validate series function NOT marking complete inside the interpolation logic
     - interpolation function should ONLY do the interpolation
- maybe change interpolation object in dspec to mandatory but if not there just sets interpolation to false?
     - true/false
     - interpolation method
     - gapDistance

2024-05-11 01:52 UTC, bestrada33 commented on src/SeriesProvider/SeriesProvider.py
> +         filled_merged_df = fill_in_date_gaps(merged_df,timeDescription.fromDateTime, timeDescription.toDateTime, timeDescription.interval,)
Just for reference, but this is what I am referring to.
![image](https://github.com/conrad-blucher-institute/semaphore/assets/74482285/56318393-308c-40f5-affe-40042a8c2b60)

See how the rest of the columns are set to NaN or NaT. They need to be filled in with either forward fill or backward fill.

2024-05-13 04:01 UTC, bestrada33 commented on src/SeriesProvider/SeriesProvider.py
> +    def __interpolate_series(self, inSeries: Series) -> Series:
Somewhere, we need to check if there is only one value being requested. If there is only one value, then we should not attempt to interpolate.

2024-05-14 03:02 UTC, bestrada33 commented on src/SeriesProvider/SeriesProvider.py
> +        if(len(validated_merged_result.data) > 1):
This won't work since we need validated_interpolation_results to be created. Will move inside the interpolate_series function

2024-05-14 19:44 UTC, matdenkas requested changes
This was so much code! Oh my god! Feel proud this work is really really solid!

2024-05-14 19:44 UTC, matdenkas commented on data/dspec/test_dspec-2-0.json
> +            "interpolationParameters": {},
This will cause issues. The get method in the parser will only apply the default if nothing is found. Technically there is something here though iirc. From my understanding this is like if we are expecting a sting and we get none/null or an empty string ('')

2024-05-14 19:44 UTC, matdenkas commented on data/dspec/test_dspec-2-0.json
> +            "interpolationParameters": {},
You can just delete the whole interpolation Parameters line

2024-05-14 19:44 UTC, matdenkas commented on src/SeriesProvider/SeriesProvider.py
> +         if interpolationParameters is None:
This should hard fail, it should raise an exception.

2024-05-14 19:44 UTC, matdenkas commented on src/SeriesProvider/SeriesProvider.py
> +         if method is None or limit is None:
Again, this should hard fail

2024-05-14 19:44 UTC, matdenkas commented on src/SeriesProvider/SeriesProvider.py
> +             log(f'''Interpolation error,
This should be concatted to the non_complete reason on the series. Basically helping to log what went wrong with the series in the object itself.

2024-05-14 19:44 UTC, matdenkas commented on src/SeriesProvider/SeriesProvider.py
> +
If you want to remove this extra condition just for the first time, you can just set previous_date to the first index's date

2024-05-14 19:44 UTC, matdenkas commented on src/SeriesProvider/SeriesProvider.py
> +        """
Amazing work! This is an impressively well written algo, I really like it!!!

2024-05-14 19:44 UTC, matdenkas commented on src/SeriesProvider/SeriesProvider.py
> +            #Taking out the entire pair including the timestamp may make it difficult to interpolate
Is this supposed to still be here? It doesn't make a lot of sense to me

2024-05-14 19:44 UTC, matdenkas commented on src/tests/UnitTests/test_Interpolation.py
> +    assert actual_length_of_data == expected_length_of_data
Really really solid test. I love how you parametrized it. As a critique watch your edge cases. A empty series and a series that doesn't actually need interpolation. But seriously, this is already a really really good test.

2024-05-14 20:08 UTC, bestrada33 commented on src/SeriesProvider/SeriesProvider.py
> +        """
<3

2024-05-14 20:14 UTC, bestrada33 commented on src/SeriesProvider/SeriesProvider.py
> +            #Taking out the entire pair including the timestamp may make it difficult to interpolate
Not sure what this was. Removed.

2024-05-14 21:13 UTC, merged