Created the hohonu data ingestion class and added a few new variables…
conrad-blucher-institute/semaphore pull request #370
Opened 2024-07-12 05:31 UTC by abeasley1722

I added the is_output and station_id variable to the seriesDescription because its needed for the hohonu API. Let me know if you think this is a good idea or not.

2024-07-31 03:13 UTC, lovelysandlonelys requested changes

2024-07-31 03:13 UTC, lovelysandlonelys commented on src/DataClasses.py
> +    def __init__(self, dataSource: str, dataSeries: str, dataLocation: str, dataDatum: str = None,  dataIntegrityDescription: DataIntegrityDescription = None, verificationOverride: int = None, is_out
regarding including the station ID in the series description, I don't think that including something in the series description that's _specific_ to a certain injestion class is necessarily a good idea. 

I was under the impression that if an ingestion class needed a specific internal location code or ID then we stored that in the semaphore database alongside the data source name: 
![image](https://github.com/user-attachments/assets/eda2025f-45bb-451d-b9ec-21c961454b4a)

it has been a while since I've looked at/worked with semaphore though so please please correct me if I'm wrong but I think that we should be utilizing our database and the ORM method below for specific station ID's 

![image](https://github.com/user-attachments/assets/0c5be242-a907-477f-883c-050ef8a36e51)

2024-07-31 03:13 UTC, lovelysandlonelys commented on src/DataIngestion/DI_Classes/HOHONU.py
> +        station_id = seriesDescription.station_id
so in line with my previous comment i think that rather than having station ID as a member of seriesDescription you would use a call to the ORM to find what hohonu calls the station that we need like this example below in the lighthouse ingestion class: 

![image](https://github.com/user-attachments/assets/5938d364-5061-4261-b32e-2f91c09f383c)

2024-07-31 03:13 UTC, lovelysandlonelys commented on src/DataIngestion/DI_Classes/HOHONU.py
> +        """This script ensures the correct interval of datapoints is being used"""
description doesn't list parameters or returns

2024-07-31 03:13 UTC, lovelysandlonelys commented on src/DataIngestion/DI_Classes/HOHONU.py
> +    def __convert_date_format(self, date):
function definition doesn't have the datatypes of passed parameter like other functions do

2024-07-31 03:13 UTC, lovelysandlonelys commented on src/DataIngestion/DI_Classes/HOHONU.py
> +    def __convert_dataframe_to_output(self,df: pd.DataFrame, timeDescription: TimeDescription) ->list[Output]:
no function description

2024-07-31 03:13 UTC, lovelysandlonelys commented on src/tests/IntegrationTests/test_HOHONU.py
> +#test_LIGHTHOUSE.py
i haven't run the test mostly because of my other comments but the other aspects of the ingestion class seem good to me.

2024-08-23 02:18 UTC, matdenkas requested changes
Can you email us the HOHONU api keys so that we can test on our machines? ty! Im not keyed in yet on whats going on with this Hohonu stuff so if anything im asking is completely ignorant my b!

2024-08-23 02:18 UTC, matdenkas commented on src/DataIngestion/DI_Classes/HOHONU.py
> +                dataUnit= "feet",
This is an imperial unit, do we want to make an exception for this? We have a strong rule that everything in the DB should be metric!

2024-08-23 02:18 UTC, matdenkas commented on src/DataIngestion/DI_Classes/HOHONU.py
> +#NDBC.py
NDBC -> HOHONU

2024-08-23 02:18 UTC, matdenkas commented on src/DataClasses.py
> +        return f'\n[TimeDescription] -> fromDateTime: {self.fromDateTime}, toDateTime: {self.toDateTime}, interval: {self.interval}, leadtime: {self.leadtime}'
Why are we adding this to this data structure? Maybe I don't know whats going on, but lead time is a attribute of a model, not a span of time. The dime description should describe the datetime properties of a dataset, meaning the span of time that the data is in, in what interval.

2024-08-23 05:25 UTC, lovelysandlonelys commented on src/DataIngestion/DI_Classes/HOHONU.py
> +                leadTime= timeDescription.leadtime
I think this is the only place where you use the leadtime? to calculate a timeVerified? 

I'm about to expose the extent to which I do not remember what is going on with the magnolia models but are we getting predictions or are we getting actual datapoints? From what you did here I'm assuming it's predictions. Does hohonu truly not give any information about when their predictions are for in the returned data? It looks like in the other ingestion classes either the time generated is used for both, or (in ndfd) the time generated is set to "None" so....... probably something we should talk about, potentially?

2024-08-23 16:17 UTC, closed without merging