362-create-the-hohonu-ingestion-class
conrad-blucher-institute/semaphore pull request #407
Opened 2024-08-23 16:25 UTC by abeasley1722

2024-08-23 18:19 UTC, lovelysandlonelys requested changes

2024-08-23 18:19 UTC, lovelysandlonelys commented on src/DataIngestion/DI_Classes/HOHONU.py
> +                timeVerified= dt + timeDescription.leadtime,
![image](https://github.com/user-attachments/assets/98d91c06-2747-4ca5-8296-de72d48d30f9)

timeDescription.leadtime doesn't exist as a part of the time description anymore, so I think here you would have to just do dt?

2024-08-23 18:19 UTC, lovelysandlonelys commented on src/tests/IntegrationTests/test_HOHONU.py
> +    (SeriesDescription(dataSource='HOHONU', dataSeries='dWl', dataLocation='MagnoliaBeach', dataDatum= 'D2W_FEET', is_output=False), TimeDescription(fromDateTime=(datetime.now() - timedelta(hours=10)
is_output is no longer a part of the series description, you also still have leadtime as a part of the time description despite taking it out of the data class itself. 

![image](https://github.com/user-attachments/assets/aa76d4ef-7633-4534-88a9-ed0a7071c14e)

2024-08-26 21:36 UTC, matdenkas requested changes
LMK if you wanna talk about this. IDK if this has been talked over with people

2024-08-26 21:36 UTC, matdenkas commented on src/DataIngestion/DI_Classes/HOHONU.py
> +                dataUnit= "feet",
We shouldn't be putting imperial units into the DB. Technically we can but we are supposed to convert to metric and then convert back out when we use it else where. There is already a system in Semaphore to do this. LMK if you need help figuring it out.

2024-08-27 18:36 UTC, merged