2.4 database migration and hohonu ingestion class
conrad-blucher-institute/semaphore pull request #424
Opened 2024-08-27 18:39 UTC by abeasley1722

2024-08-28 15:35 UTC, matdenkas requested changes
This is a tone of work and it looks very well done. Tests are currently failing on my machine though after building. Once we know they are passing then this LGTM!!!!

2024-08-28 15:35 UTC, matdenkas commented on src/DataIngestion/DI_Classes/HOHONU.py
> +#NDBC.py
Super nit picky NDBC -> HOHONU

2024-08-28 15:35 UTC, matdenkas commented on src/DataIngestion/DI_Classes/HOHONU.py
> +    def mm_to_m(self, mm):
Method should be private. Again super nit picky feel free to ignore

2024-08-28 15:35 UTC, matdenkas commented on src/Frontend/ChartJson/Magnolia_Bay.json
> +{
Cant review, ive no clue what this is lol

2024-08-28 15:35 UTC, matdenkas commented on src/tests/IntegrationTests/test_HOHONU.py
> +# -*- coding: utf-8 -*-
THESE ARE WAAAAAAY BETTER tests! Thank you for making that change. However im afraid they are failing on my machine.

![image](https://github.com/user-attachments/assets/278b6a7f-76f4-4b30-9114-5ed553c5e003)

2024-08-28 15:35 UTC, matdenkas commented on tools/DatabaseMigration/2_4/2_4_DatabaseMigration.py
> +# -*- coding: utf-8 -*-
Perfect! Works going up and rolling back!

2024-08-28 15:35 UTC, matdenkas commented on src/DataIngestion/DI_Classes/HOHONU.py
> +                dataValue= value,
TY for fixing this!

2024-08-28 17:03 UTC, lovelysandlonelys requested changes
The tests are also failing for me! I think that it might be some kind of importing issue 😥 

![image](https://github.com/user-attachments/assets/34b29ecb-72e2-481a-8052-05d9f0684476)

This is a screenshot of some testing I ran. All of the results.data items ARE Inputs, however isinstance() is treating 'Input' and '< DataClasses.Input' > as two differnt things. Maybe! I just poked around a little. 

here's the code i used: 
for item in result.data :
            print(f'input: {item} \n[Type] -> {type(item)}')
            print(f'Is Instance of Input: {isinstance(item, Input)}')
            print(f'IDs: ')
            print(f'Input ID {id(Input)}')
            print(f'item ID {id(type(item))}')

2024-09-13 04:32 UTC, matdenkas approved these changes
LGTM! That was a slog! You deserve ice cream!

2024-09-13 04:32 UTC, matdenkas commented on src/tests/IntegrationTests/test_HOHONU.py
> +# -*- coding: utf-8 -*-
All tests passing

2024-09-13 04:32 UTC, matdenkas commented on src/tests/IntegrationTests/test_HOHONU.py
> +        assert False, "The result is None"
I had no idea you could just tack a string onto an assertion! Rad

2024-09-18 00:24 UTC, merged