DB Migration 2.5
conrad-blucher-institute/semaphore pull request #425
Opened 2024-08-28 16:49 UTC by matdenkas

Steps to test: 
1. Delete your local DB volume.
2. Build and run `docker exec semaphore-core python3 tools/migrate_db.py` to test update to 2.5, validate with PGAdmin that rows are correct. (or don't im not your boss)
3. Edit target_version.json: 2.5->2.3 and rebuild.
4. Run `docker exec semaphore-core python3 tools/migrate_db.py` to test rollback, validate with PGAdmin that rows are correct. (or don't im not your boss)

2024-08-28 17:34 UTC, lovelysandlonelys requested changes
Just documentation changes, everything else looks great and tests run perfectly. 
![image](https://github.com/user-attachments/assets/3afa4faf-1ed2-4962-bcec-c9b17e725cda)

2024-08-28 17:34 UTC, lovelysandlonelys commented on tools/DatabaseMigration/2_5/2_5_DatabaseMigration.py
> +        """This function updates the database to version 2.2 which adds rows to the locations reference
function description says we're updating to version 2.2 🤩

2024-08-28 17:34 UTC, lovelysandlonelys commented on tools/DatabaseMigration/2_5/2_5_DatabaseMigration.py
> +        """This function rolls the database back to version 2.1 which involves removing the changes
Rollback function description says we're rolling back to 2.1 from 2.2

2024-08-28 18:47 UTC, matdenkas commented on tools/DatabaseMigration/2_5/2_5_DatabaseMigration.py
> +        """This function updates the database to version 2.2 which adds rows to the locations reference
I DIDNT STEAL YOUR CODE

2024-08-28 18:47 UTC, matdenkas commented on tools/DatabaseMigration/2_5/2_5_DatabaseMigration.py
> +        """This function rolls the database back to version 2.1 which involves removing the changes
Okay... maybe I stole your code

2024-08-28 18:48 UTC, matdenkas commented on tools/DatabaseMigration/2_5/2_5_DatabaseMigration.py
> +        """This function updates the database to version 2.2 which adds rows to the locations reference
Fixed!

2024-08-28 18:48 UTC, matdenkas commented on tools/DatabaseMigration/2_5/2_5_DatabaseMigration.py
> +        """This function rolls the database back to version 2.1 which involves removing the changes
Fixed!

2024-08-28 18:52 UTC, lovelysandlonelys approved these changes

2024-08-30 17:08 UTC, abeasley1722 approved these changes
LGTM

2024-08-30 17:16 UTC, abeasley1722 commented on tools/DatabaseMigration/2_4/2_4_DatabaseMigration.py
> +        """This function updates the database to version 2.5 which update Series descriptions
2.4*

2024-08-30 17:17 UTC, merged