438 update surge models to dspec 20
conrad-blucher-institute/semaphore pull request #439
Opened 2024-09-13 03:07 UTC by matdenkas

Updating thermal refuge dspec to 2.0. 

To check this PR... its gonna suck. I wrote a checklist you can find here:
https://docs.google.com/spreadsheets/d/1eV9fRGkZnrJYPFxOCErO9p_oEVL2Mu1whJM-uyYW-30/edit?usp=sharing

Besides that its just comparing the old and new version determining no mistakes were made in the update. Sorry 😭 

```
docker exec semaphore-core python3 src/semaphoreRunner.py -d ./Surge/Rockport/rp_mlp_surge_72h_pred.json -p 2024091201
docker exec semaphore-core python3 src/semaphoreRunner.py -d ./Surge/Rockport/rp_mlp_surge_48h_pred.json -p 2024091201
docker exec semaphore-core python3 src/semaphoreRunner.py -d ./Surge/Rockport/rp_mlp_surge_24h_pred.json -p 2024091201
docker exec semaphore-core python3 src/semaphoreRunner.py -d ./Surge/Rockport/rp_mlp_surge_12h_pred.json -p 2024091201

docker exec semaphore-core python3 src/semaphoreRunner.py -d ./Surge/Port_Isabel/pi_mlp_surge_72h_pred.json -p 2024091201
docker exec semaphore-core python3 src/semaphoreRunner.py -d ./Surge/Port_Isabel/pi_mlp_surge_48h_pred.json -p 2024091201
docker exec semaphore-core python3 src/semaphoreRunner.py -d ./Surge/Port_Isabel/pi_mlp_surge_24h_pred.json -p 2024091201
docker exec semaphore-core python3 src/semaphoreRunner.py -d ./Surge/Port_Isabel/pi_mlp_surge_12h_pred.json -p 2024091201

docker exec semaphore-core python3 src/semaphoreRunner.py -d ./Surge/North_Jetty/nj_mlp_surge_72h_pred.json -p 2024091201
docker exec semaphore-core python3 src/semaphoreRunner.py -d ./Surge/North_Jetty/nj_mlp_surge_48h_pred.json -p 2024091201
docker exec semaphore-core python3 src/semaphoreRunner.py -d ./Surge/North_Jetty/nj_mlp_surge_24h_pred.json -p 2024091201
docker exec semaphore-core python3 src/semaphoreRunner.py -d ./Surge/North_Jetty/nj_mlp_surge_12h_pred.json -p 2024091201

docker exec semaphore-core python3 src/semaphoreRunner.py -d ./Surge/Aransas/ar_mlp_surge_72h_pred.json -p 2024091201
docker exec semaphore-core python3 src/semaphoreRunner.py -d ./Surge/Aransas/ar_mlp_surge_48h_pred.json -p 2024091201
docker exec semaphore-core python3 src/semaphoreRunner.py -d ./Surge/Aransas/ar_mlp_surge_24h_pred.json -p 2024091201
docker exec semaphore-core python3 src/semaphoreRunner.py -d ./Surge/Aransas/ar_mlp_surge_12h_pred.json -p 2024091201
```

2024-09-13 03:07 UTC, matdenkas commented
I supplied some commands, but be ready to wrestle with NDFD. Running the 72 hour model first will get you all your data for that location!

2024-09-18 18:47 UTC, abeasley1722 commented on data/dspec/Surge/Aransas/ar_mlp_surge_12h_pred.json
> +            "_name": "for surge now actuals",
Maybe "nowTimeSurgeActuals" is a better name?

2024-09-18 18:47 UTC, abeasley1722 commented on data/dspec/Surge/Aransas/ar_mlp_surge_12h_pred.json
> +            "series": "dWl",
Why is this dWl and not dSurge like in the 1.0 dspec?

2024-09-18 19:00 UTC, lovelysandlonelys requested changes

2024-09-18 19:00 UTC, lovelysandlonelys commented on data/dspec/Surge/Aransas/ar_mlp_surge_12h_pred.json
> +            "call": "ArithmeticOperation",
if we're calling arithmetic operation on dwaterlevel and pwaterlevel then should we remove the __fetch_dSurge function from NOAATANDC since this is the same thing?

2024-09-18 19:00 UTC, lovelysandlonelys commented on data/dspec/Surge/Port_Isabel/pi_mlp_surge_12h_pred.json
> +            "location": "Aransas",
"location": "PortIsabel",

2024-09-18 19:00 UTC, lovelysandlonelys commented on data/dspec/Surge/Port_Isabel/pi_mlp_surge_12h_pred.json
> +            "location": "Aransas",
"location": "PortIsabel",

2024-09-18 19:00 UTC, lovelysandlonelys commented on data/dspec/Surge/Port_Isabel/pi_mlp_surge_12h_pred.json
> +            "location": "Aransas",
"location": "PortIsabel",

2024-09-18 19:00 UTC, lovelysandlonelys commented on data/dspec/Surge/Port_Isabel/pi_mlp_surge_12h_pred.json
> +            "location": "Aransas",
"location": "PortIsabel",

2024-09-18 19:00 UTC, lovelysandlonelys commented on data/dspec/Surge/Port_Isabel/pi_mlp_surge_12h_pred.json
> +            "location": "Aransas",
"location": "PortIsabel",

2024-09-18 19:00 UTC, lovelysandlonelys commented on data/dspec/Surge/Port_Isabel/pi_mlp_surge_12h_pred.json
> +            "location": "Aransas",
okay so i think all the locations in this file are wrong but that seems like the only issue so far

2024-09-18 19:02 UTC, lovelysandlonelys commented on data/dspec/Surge/Aransas/ar_mlp_surge_12h_pred.json
> +            "_name": "for surge now actuals",
_name is just a comment, i think it's good as it is since the two series with this name are used in the post processing call for surge

2024-09-18 19:03 UTC, lovelysandlonelys commented on data/dspec/Surge/Aransas/ar_mlp_surge_12h_pred.json
> +            "series": "dWl",
because we're calculating the surge using the dwl and pwl i think

2024-09-18 19:40 UTC, matdenkas commented on data/dspec/Surge/Aransas/ar_mlp_surge_12h_pred.json
> +            "call": "ArithmeticOperation",
Yes. But not right now. Its my understanding that to safely refactor something like this, we first raise the dependencies to the new version, then we depreciate the old cold and remove it. My plan was to do this in two phases and once all these are approved go and refactor the ingestion classes and depricate the stuff in the DB

2024-09-18 19:41 UTC, matdenkas commented on data/dspec/Surge/Port_Isabel/pi_mlp_surge_12h_pred.json
> +            "location": "Aransas",
DAMN!
Oh my god nice catch! Thank you so much! I will fix this!!!

2024-09-19 02:57 UTC, lovelysandlonelys commented on data/dspec/Surge/Aransas/ar_mlp_surge_12h_pred.json
> +            "call": "ArithmeticOperation",
Ah that makes sense! Safer to do things in stages

2024-09-19 19:10 UTC, matdenkas commented on data/dspec/Surge/Port_Isabel/pi_mlp_surge_12h_pred.json
> +            "location": "Aransas",
Just fixed it, literally I had done it but I didnt save the file. AHHHHHHH!
Thank you again for the catch

2024-09-19 21:55 UTC, lovelysandlonelys requested changes

2024-09-19 21:55 UTC, lovelysandlonelys commented on data/dspec/Surge/Port_Isabel/pi_mlp_surge_12h_pred.json
> +            "location": "Aransas",
Hi matthew, still showing as aransas in this file for me?

2024-09-19 21:55 UTC, lovelysandlonelys commented on data/dspec/Magnolia/12/magnolia_12.json
> +    "modelVersion": "2.0.0",
why... only change this one

2024-09-20 01:21 UTC, matdenkas commented on data/dspec/Surge/Port_Isabel/pi_mlp_surge_12h_pred.json
> +            "location": "Aransas",
I did something silly. Thank you for your patience. this should be fixed now

2024-09-25 14:15 UTC, abeasley1722 approved these changes
LGTM other than ndfd returning none sometimes per usual

2024-10-17 18:13 UTC, merged