456 update inundation models to dspec 20
conrad-blucher-institute/semaphore pull request #471
Opened 2024-09-23 21:34 UTC by matdenkas

Finally the inundation models are done. There is a warning in the PPC for low values and a new way of doing series overrides. 

Here is the script I used to test this

```
import subprocess
from datetime import datetime
MONTHS = [ "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" ]
MONTS_ABRIVE = ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']
LEAD_TIMES = ['12', '24', '48']
START_TIME = datetime(2024, 9, 14, 00, 00)

for month, month_abrive in zip(MONTHS, MONTS_ABRIVE):
    for lead_time in LEAD_TIMES:
        time_str = START_TIME.strftime('%Y%m%d%H') + '01'
        cmd = f'./Inundation/{month}/ar_inundation_{month_abrive}_{lead_time}h.json'
        proc = subprocess.run(["docker", "exec", "semaphore-core", "python3", "src/semaphoreRunner.py", "-d", cmd, '-p', time_str]) 
        print(f'----------------------PROC RETURN {proc.returncode}----------------------')
        
```

2024-09-25 15:44 UTC, abeasley1722 requested changes
This was a TON of work. Thank you for handling this. All tests and models ran as expected except for one failure in the unit_seriesProvider. Other than that, and the misspelled word everything works perfectly.

2024-09-25 15:44 UTC, abeasley1722 commented on src/SeriesProvider/SeriesProvider.py
> +            case 'graterThanOrEqual':
Nitpicky and requires to change a lot of files, but it should be greaterThanOrEqual.

2024-09-25 15:44 UTC, abeasley1722 commented on src/tests/UnitTests/test_unit_SeriesProvider.py
>  TEST_DI_DESC_MISS_1 = SeriesDescription('TEST_DI', 'MISS_1', 'TEST', None)
One test failed 
![image](https://github.com/user-attachments/assets/09df7e88-a37a-4156-89c8-4eac87bd21a7)
![Screenshot 2024-09-25 103628](https://github.com/user-attachments/assets/be767e1e-2e37-4dee-b7ce-ae05e6a07040)

2024-10-07 19:33 UTC, lovelysandlonelys approved these changes
![image](https://github.com/user-attachments/assets/5cbddc65-c2ef-44d0-a78e-fdc175c675ad)
![image](https://github.com/user-attachments/assets/bf16e7e6-a12e-4cf2-98a9-f92935039a3f)

Tests all passed for me and the models ran with the demo code provided.

2024-10-07 21:59 UTC, matdenkas commented on src/SeriesProvider/SeriesProvider.py
> +            case 'graterThanOrEqual':
Fixed! Ty for the spell check!

2024-10-07 22:02 UTC, matdenkas commented on src/tests/UnitTests/test_unit_SeriesProvider.py
>  TEST_DI_DESC_MISS_1 = SeriesDescription('TEST_DI', 'MISS_1', 'TEST', None)
Test sometimes passes and sometimes fails. Seems to be to do with the interpolation. Out of scope for this PR

2024-10-17 18:14 UTC, merged