Base of Frontend and its docker container
conrad-blucher-institute/semaphore pull request #477
Opened 2024-09-30 15:27 UTC by abeasley1722

This is the base of the Vue app and frontend's docker container. The docker container will run a development server. This, of course, will be changed when we're ready for production. Run the containers like usual and confirm that localhost 8080 shows a blank white screen with "Semaphore" and a drop down menu. It looks very bland since I will be focusing on visuals last and logic first. (Other than the styes on the dropdown menu).
![image](https://github.com/user-attachments/assets/d0123739-360c-4365-b55f-25a9e5c98f81)

2024-10-07 21:50 UTC, matdenkas requested changes
Nice work, this is all very exciting. To much future front-ending 🥂 


Just a few changes about the CI/CD pipeline, not the most important stuff though:
- port missing from env.dist
- We might have to build before running the server
- Careful about exposing tones of envs, no we are not most secure but with things like authentication token, it should always be need to know.

2024-10-07 21:50 UTC, matdenkas commented on docker-compose.yml
> +    environment:
Do we need to expose all of these envs?

2024-10-07 21:50 UTC, matdenkas commented on docker-compose.yml
> +      - "${FRONTEND_HOST_PORT}:8080"
This needs to be added to .env.dist

2024-10-07 21:50 UTC, matdenkas commented on Dockerfile.frontend
> +CMD ["npm", "run", "serve"]
Do we not need to run build first? This might also need to be added to our CI/CD script, we certainly shouldn't be putting the built frontend on git hub. Ive not used vue so I could be wrong about having to build it.

2024-10-07 21:50 UTC, matdenkas commented on Dockerfile.frontend
> +COPY ./src/Frontend/semaphore-ui/ ./
Putting this here but it doesn't have to do with this line. Under frontend there is .src/Frontend/ChartJson/ ... I feel this would be better under the ./docs folder like how the other dspecs are. No reason for this to block this PR though.

2024-10-09 00:33 UTC, lovelysandlonelys approved these changes
Well done!!!! From what I can understand everything looks good to me and page displayed as expected.

2024-10-10 16:27 UTC, abeasley1722 commented on Dockerfile.frontend
> +COPY ./src/Frontend/semaphore-ui/ ./
Makes sense

2024-10-10 16:31 UTC, abeasley1722 commented on Dockerfile.frontend
> +CMD ["npm", "run", "serve"]
We will need to build in the production version of the dockerfile. The serve command handles everything needed for Vue's development server.

2024-10-10 16:38 UTC, abeasley1722 commented on src/Frontend/semaphore-ui/public/index.html
> +<html lang="">
Good catch. This was automatically made by Vue. I forgot t add en.

2024-10-11 19:29 UTC, snguyen1 requested changes

2024-10-11 19:29 UTC, snguyen1 commented on Dockerfile.frontend
> +FROM node:14 AS build
Consider moving to new node version since 14 is being deprecated:
https://endoflife.date/nodejs
Also, some Vue + TypeScript versions only compatible with some certain node versions.

2024-10-11 19:40 UTC, snguyen1 requested changes

2024-10-11 19:40 UTC, snguyen1 commented on src/Frontend/semaphore-ui/package.json
> +    "vue": "^3.2.13"
may need to update to a newer version of Vue. Depends on what version of node we're going for.

2024-10-14 15:58 UTC, snguyen1 requested changes

2024-10-14 15:58 UTC, snguyen1 commented on Dockerfile.frontend
> +COPY ./package-lock.json ./
Ideally, package.json and package-lock.json should be in the same folder on host. Looks like package-lock.json was copied from the root working directory instead of `.src/Frontend....` like package.json

2024-11-04 17:26 UTC, closed without merging