444 meta table for semaphore failing
conrad-blucher-institute/semaphore pull request #478
Opened 2024-10-07 21:34 UTC by matdenkas

To test you can run test:
`docker exec semaphore-core python3 -m pytest`

Try running a model:
`docker exec semaphore-core python3 src/semaphoreRunner.py -d TestModels/test_dspec.json`

You can also cause semaphore to fail somewhere.

You can see the results by querying the db:
SELECT * FROM outputs
JOIN model_runs ON outputs."id" = model_runs."outputID"

This PR contains a DB migration script, the number might need to be changed on merge

2024-10-09 05:06 UTC, lovelysandlonelys requested changes
![image](https://github.com/user-attachments/assets/bf7d7a7b-1e52-4610-93e7-c09cbdf66d27)
Tests Passed
Just tiny documentation changes, everything else looks right to me.

2024-10-09 05:06 UTC, lovelysandlonelys commented on tools/DatabaseMigration/2_6/2_6_DatabaseMigration.py
> +CSV_FILE_PATHS = './tools/DatabaseMigration/1_0/init_data'
CSV file path 1_0! I think you can just fully remove this line.

2024-10-09 05:06 UTC, lovelysandlonelys commented on tools/DatabaseMigration/2_6/2_6_DatabaseMigration.py
> +        """This function updates the database to version 1.0 which includes the base schema and data locations.
incorrect function documentation 😭

2024-10-09 21:13 UTC, lovelysandlonelys commented on tools/DatabaseMigration/2_6/2_6_DatabaseMigration.py
> +        """This function updates the database to version 1.0 which includes the base schema and data locations.
?? still here

2024-10-09 21:15 UTC, matdenkas commented on tools/DatabaseMigration/2_6/2_6_DatabaseMigration.py
> +        """This function updates the database to version 1.0 which includes the base schema and data locations.
SO SO SO MY BAD! Didn't push, sorry for the extra ping

2024-10-10 16:04 UTC, abeasley1722 commented on src/semaphoreRunner.py
> +            input_gatherer = InputGatherer(fileName)
Good improvement to the variable name

2024-10-10 22:51 UTC, abeasley1722 commented
Tests Passed

2024-10-11 17:39 UTC, lovelysandlonelys approved these changes
It's looking like this will go in first so like joy said, might have to change to 2.5 but otherwise 👍🏻

2024-10-17 18:39 UTC, merged