90 refactor dataclasses to reflect new schema
conrad-blucher-institute/semaphore pull request #91
Opened 2023-10-11 01:17 UTC by bestrada33

2023-10-11 02:01 UTC, abeasley1722 approved these changes

2023-10-11 23:40 UTC, abeasley1722 approved these changes

2023-10-12 01:36 UTC, lovelysandlonelys requested changes
1) interval changed to timeDalta
2) don't include timeAquired, timeVerified, timeGenreated, in the Input class (this is Matthew's fault because the objects class diagram in Miro wasn't updated to reflect the classes with the new time object)
3)changes should be submitted to the schemaRefactorBranch not main branch (we already fixed this for you xoxo)

2023-10-12 01:43 UTC, matdenkas approved these changes

2023-10-12 01:43 UTC, lovelysandlonelys approved these changes
no notes <3

2023-10-12 01:44 UTC, merged